# Generated by Django 5.0.6 on 2025-11-26 12:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HindiNews',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(db_column='headline', max_length=500)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('short_description', models.CharField(blank=True, db_column='short_description', max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(db_column='location', max_length=45, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('audio_location', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('TELUGU', 'TELUGU'), ('KANNADA', 'KANNADA'), ('MALAYALAM', 'MALAYALAM'), ('MARATHI', 'MARATHI'), ('TAMIL', 'TAMIL')], db_column='language', default='HINDI', max_length=50)),
                ('url', models.URLField(blank=True, max_length=5000, null=True)),
                ('is_published', models.CharField(choices=[('NOT_PUBLISHED', 'NOT_PUBLISHED'), ('PUBLISHED', 'PUBLISHED')], db_column='is_published', default='NOT_PUBLISHED', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hindi_news',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'article_category',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
                ('priority_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='FixedHoliday',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fixed_holidays',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='MovieHeader',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
            options={
                'db_table': 'movie_header',
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'organization_category',
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.CharField(db_column='id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('surname', models.CharField(db_column='surname', max_length=200)),
                ('full_name', models.CharField(db_column='full_name', max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=10, unique=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=50)),
                ('dob', models.DateField()),
                ('gotram', models.CharField(blank=True, max_length=200)),
                ('verification_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_otp_created_time', models.DateTimeField(null=True)),
                ('verification_otp_resend_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', max_length=50)),
                ('forgot_password_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('forgot_password_otp_created_time', models.DateTimeField(null=True)),
                ('forgot_password_otp_resend_count', models.IntegerField(default=0)),
                ('is_member', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=50)),
                ('type', models.CharField(choices=[('MEMBER', 'MEMBER '), ('PUJARI', 'PUJARI')], db_column='type', default='MEMBER ', max_length=50)),
                ('pujari_certificate', models.TextField(blank=True, db_column='pujari_certificate', null=True)),
                ('working_temple', models.CharField(blank=True, db_column='working_temple', max_length=150, null=True)),
                ('account_type', models.CharField(max_length=10)),
                ('stakeholder_type', models.CharField(max_length=10)),
                ('family_images', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.TextField(blank=True, db_column='headline', null=True)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('short_description', models.TextField(blank=True, db_column='short_description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(db_column='location', max_length=45, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('audio_location', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('TELUGU', 'TELUGU'), ('KANNADA', 'KANNADA'), ('MALAYALAM', 'MALAYALAM'), ('MARATHI', 'MARATHI'), ('TAMIL', 'TAMIL')], db_column='language', default='ENGLISH', max_length=50)),
                ('is_published', models.CharField(choices=[('NOT_PUBLISHED', 'NOT_PUBLISHED'), ('PUBLISHED', 'PUBLISHED')], db_column='is_published', default='NOT_PUBLISHED', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.CharField(help_text='Enter the year in YYYY format.', max_length=4, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid year.', regex='^\\d{4}$')])),
                ('category_id', models.ForeignKey(db_column='category_id', max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='hindupulseapp.articlecategory')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='ArticleProfile',
            fields=[
                ('id', models.CharField(db_column='id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, db_column='desc', max_length=5000, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('is_member', models.CharField(choices=[('true', 'true'), ('false', 'false')], default='false', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('article', models.ForeignKey(db_column='article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_model', to='hindupulseapp.articlemodel')),
            ],
            options={
                'db_table': 'article_profile',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='article_user',
            field=models.ForeignKey(db_column='article_user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_user', to='hindupulseapp.articleprofile'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(db_column='body', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reply', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('articles', models.ForeignKey(blank=True, db_column='articles', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='hindupulseapp.articlemodel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hindupulseapp.commentmodel')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovieGeners',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geners', to='hindupulseapp.movieheader')),
            ],
            options={
                'db_table': 'movie_all_geners',
            },
        ),
        migrations.CreateModel(
            name='MoviePlatforms',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('website_links', models.URLField(blank=True, null=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='hindupulseapp.movieheader')),
            ],
            options={
                'db_table': 'movie_all_platforms',
            },
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.JSONField(blank=True, db_column='poster', null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('trailer', models.JSONField(blank=True, db_column='trailer', default=list, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('trailer_link', models.URLField(blank=True, null=True)),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='hindupulseapp.language')),
                ('user_id', models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_details', to=settings.AUTH_USER_MODEL)),
                ('geners_id', models.ForeignKey(blank=True, db_column='geners_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='hindupulseapp.moviegeners')),
                ('header_id', models.ForeignKey(blank=True, db_column='header_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='hindupulseapp.movieheader')),
                ('platform_id', models.ForeignKey(blank=True, db_column='platform_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='hindupulseapp.movieplatforms')),
            ],
            options={
                'db_table': 'movie_details',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(db_column='headline', max_length=500)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('short_description', models.CharField(blank=True, db_column='short_description', max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(db_column='location', max_length=45, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('audio_location', models.TextField(blank=True, null=True)),
                ('media', models.JSONField(blank=True, default=list, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('TELUGU', 'TELUGU'), ('KANNADA', 'KANNADA'), ('MALAYALAM', 'MALAYALAM'), ('MARATHI', 'MARATHI'), ('TAMIL', 'TAMIL')], db_column='language', default='ENGLISH', max_length=50)),
                ('url', models.URLField(blank=True, max_length=5000, null=True)),
                ('is_published', models.CharField(choices=[('NOT_PUBLISHED', 'NOT_PUBLISHED'), ('PUBLISHED', 'PUBLISHED')], db_column='is_published', default='NOT_PUBLISHED', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.ForeignKey(max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_id', to='hindupulseapp.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsCommentModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(db_column='body', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reply', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('news', models.ForeignKey(blank=True, db_column='news', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='hindupulseapp.newscategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hindupulseapp.newscommentmodel')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewsSubCategory',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('other_category', models.ForeignKey(db_column='category_id1', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='category_id1', to='hindupulseapp.category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.AddField(
            model_name='newscategory',
            name='news_sub_category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_sub_category_id', to='hindupulseapp.newssubcategory'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('media', models.JSONField(blank=True, default=list, null=True)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('other_category', models.ForeignKey(db_column='category_id1', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='category_id1', to='hindupulseapp.newssubcategory')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('profile_pic', models.TextField(blank=True, null=True)),
                ('organization_link', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(db_column='location', max_length=45, null=True)),
                ('priority_order', models.IntegerField(default=0)),
                ('organization_category', models.ForeignKey(db_column='organization_category', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='organization_category', to='hindupulseapp.organizationcategory')),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OutlookCommentModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('body', models.CharField(db_column='body', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reply', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('news', models.ForeignKey(blank=True, db_column='news', max_length=1000, null=True, on_delete=django.db.models.deletion.CASCADE, to='hindupulseapp.newssubcategory')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='hindupulseapp.outlookcommentmodel')),
                ('user', models.ForeignKey(db_column='user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlook_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outlook_comment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('other_category', models.ForeignKey(db_column='other_category', max_length=45, on_delete=django.db.models.deletion.CASCADE, related_name='poll_status', to='hindupulseapp.newssubcategory')),
            ],
            options={
                'db_table': 'poll',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StagingModel',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('headline', models.CharField(db_column='headline', max_length=500)),
                ('desc', models.TextField(blank=True, db_column='desc', null=True)),
                ('short_description', models.CharField(blank=True, db_column='short_description', max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(db_column='location', max_length=45, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('INACTIVE', 'INACTIVE')], default='PENDING', max_length=50)),
                ('image_location', models.JSONField(blank=True, default=list, null=True)),
                ('audio_location', models.TextField(blank=True, null=True)),
                ('media', models.JSONField(blank=True, default=list, null=True)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('HINDI', 'HINDI'), ('TELUGU', 'TELUGU'), ('KANNADA', 'KANNADA'), ('MALAYALAM', 'MALAYALAM'), ('MARATHI', 'MARATHI'), ('TAMIL', 'TAMIL')], db_column='language', default='ENGLISH', max_length=50)),
                ('url', models.URLField(blank=True, max_length=5000, null=True)),
                ('is_published', models.CharField(choices=[('NOT_PUBLISHED', 'NOT_PUBLISHED'), ('PUBLISHED', 'PUBLISHED')], db_column='is_published', default='NOT_PUBLISHED', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('category_id', models.ForeignKey(max_length=45, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_category_id', to='hindupulseapp.category')),
                ('news_sub_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_news_sub_category_id', to='hindupulseapp.newssubcategory')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_add_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staging_news',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StagingMovieDetails',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.JSONField(blank=True, db_column='poster', null=True)),
                ('release_date', models.CharField(blank=True, max_length=100, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('trailer', models.JSONField(blank=True, db_column='trailer', default=list, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('STAGING', 'STAGING'), ('SUCCESS', 'SUCCESS'), ('PRODUCTION', 'PRODUCTION')], default='STAGING', max_length=50)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('trailer_link', models.URLField(blank=True, null=True)),
                ('geners_id', models.ForeignKey(blank=True, db_column='geners_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_movie_details', to='hindupulseapp.moviegeners')),
                ('header_id', models.ForeignKey(blank=True, db_column='header_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_movie_details', to='hindupulseapp.movieheader')),
                ('language', models.ForeignKey(blank=True, db_column='language', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_movie_details', to='hindupulseapp.language')),
                ('platform_id', models.ForeignKey(blank=True, db_column='platform_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staging_movie_details', to='hindupulseapp.movieplatforms')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_movie_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staging_movie_details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PollResponse',
            fields=[
                ('_id', models.CharField(db_column='_id', default=uuid.uuid1, editable=False, max_length=45, primary_key=True, serialize=False, unique=True)),
                ('response', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(db_column='Poll', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='hindupulseapp.poll')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='polling_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'poll_responce',
                'unique_together': {('poll', 'user')},
            },
        ),
    ]
