"""
Django settings for hindupulseproject project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import datetime, timedelta
from dotenv import load_dotenv
load_dotenv()



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4mdj#$%___+p9#61($sfx-b#8#j+0*gx(2t5%6ld+^l)+b!t1@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# ALLOWED_HOSTS = [ ]


ALLOWED_HOSTS = ['hp-apiserver01.sts.com', 'hp-apiserver02.sts.com', '74.225.174.113']



# ALLOWED_HOSTS = ['VM-APIServer02', '4.213.197.208', 'hp-apiserver02.sts.com']

AUTH_USER_MODEL = 'hindupulseapp.Register'
# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

CORS_ALLOW_ALL_ORIGINS = True

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGGING = {
     'version': 1,
     'disable_existing_loggers': False,
     'handlers': {
         'file': {
             'level': 'DEBUG',
             'class': 'logging.FileHandler',
             'filename': os.path.join(BASE_DIR, 'django.log'),
         },
     },
     'root': {
         'handlers': ['file'],
         'level': 'DEBUG',
         'propagate': True,
     },
 }




# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_celery_beat',
    'django_filters',
    'hindupulseapp',
    'drf_yasg',
    'rest_framework',
    'corsheaders',
    'background_task'
    # 'django_celery_beat',
]


#CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:4200",
#     "http://localhost:8787"
#     # Add other allowed origins as needed
# ]
#CORS_ALLOWED_ORIGINS = [
#    "http://localhost:4200",
#    "http://localhost:8787"
    # Add other allowed origins as needed
#]





# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
# ]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST BE FIRST
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    # Optionally, you might have other configurations, such as authentication backends.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
        # Add other authentication classes if needed
    ],
    #  'DEFAULT_PAGINATION_CLASS': 'hindupulseapp.pagination.CustomPagination',
    # 'PAGE_SIZE': 50,
}


# AUTHENTICATION_BACKENDS = [
#     'django.contrib.auth.backends.ModelBackend',
# ]

# SIMPLE_JWT = {
#     # how long the original token is valid for
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=90),

#     # allow refreshing of tokens
#     'JWT_ALLOW_REFRESH': True,

#     # this is the maximum time AFTER the token was issued that
#     # it can be refreshed.  exprired tokens can't be refreshed.
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
#     'SIGNING_KEY': 'SSO_GLOBAL_SECRET_2025',  # SAME for both projects
#     'ALGORITHM': 'HS256',
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }
 




# from datetime import timedelta

# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(days=90),
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=90),
#     'SIGNING_KEY': 'SSO_GLOBAL_SECRET_2025',  # 🔴 MUST BE SAME
#     'ALGORITHM': 'HS256',
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # 🔥 MUST BE SAME IN ALL PROJECTS
    'SIGNING_KEY': 'GRAMDEVATA_SANATANA_COMMON_SECRET_2025',

    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}





ROOT_URLCONF = 'hindupulseproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hindupulseproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv("DB_ENGINE"),
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'ssl_mode': 'REQUIRED',
        },
    },
    'user_db': {
        'ENGINE': os.getenv("LOGIN_DB_ENGINE"),
        'NAME': os.getenv("LOGIN_DB_NAME"),
        'USER': os.getenv("LOGIN_DB_USER"),
        'PASSWORD': os.getenv("LOGIN_DB_PASSWORD"),
        'HOST': os.getenv("LOGIN_DB_HOST"),
        'PORT': os.getenv("LOGIN_DB_PORT"),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'ssl_mode': 'REQUIRED',
        },
    },
    'staging_db': {
        'ENGINE': os.getenv("STAGING_DB_ENGINE"),
        'NAME': os.getenv("STAGING_DB_NAME"),
        'USER': os.getenv("STAGING_DB_USER"),
        'PASSWORD': os.getenv("STAGING_DB_PASSWORD"),
        'HOST': os.getenv("STAGING_DB_HOST"),
        'PORT': os.getenv("STAGING_DB_PORT"),
        'OPTIONS': {

            'charset': 'utf8mb4',
            'ssl_mode': 'REQUIRED',
        },
    },
}

DATABASE_ROUTERS = ['hindupulseproject.db_routers.RegisterRouter']



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
        }
    }
}



SMS_USER = os.getenv('SMS_USER')
SMS_PASSWORD = os.getenv('SMS_PASSWORD')
SMS_SENDER = os.getenv('SMS_SENDER')
SMS_TYPE = os.getenv('SMS_TYPE')
SMS_TEMPLATE_ID = os.getenv('SMS_TEMPLATE_ID')
RE_SMS_TEMPLATE_ID = os.getenv('RE_SMS_TEMPLATE_ID')

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


AZURE_STORAGE_CONNECTION_STRING = os.getenv('AZURE_CONNECTION_STRING')
AZURE_CONTAINER_NAME = os.getenv('AZURE_CONTAINER_NAME')
AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')

# SARVAM_AI_API_KEY = os.getenv('SARVAM_AI_API_KEY')
# SARVAM_AI_API_URL = os.getenv('SARVAM_AI_API_URL')
SARVAM_TRANSLATE_URL = "https://api.sarvam.ai/translate"
SARVAM_API_KEY = "sk_9e0skwia_zrpuG5KvmjicCUAyxqjwpuA4"
SARVAM_TTS_URL = "https://api.sarvam.ai/tts"



# THIRD_PARTY_API_URL_POST=os.getenv('THIRD_PARTY_API_URL_POST')
# THIRD_PARTY_API_URL_GET=os.getenv('THIRD_PARTY_API_URL_GET')


FILE_URL=os.getenv('File_Path')
# FILE_URL1=os.getenv('File_Path1')


# settings.py




CELERY_BROKER_URL = 'redis://:root@localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://:root@localhost:6379/0'




from celery import Celery
from celery.schedules import crontab

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'publish-scheduled-news-every-minute': {
        'task': 'hindupulseapp.tasks.publish_scheduled_news',
        # 'schedule': 1.0,  # Run every second
        'schedule': crontab(minute='*'),  # Run every minute
    },
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




CACHE_PWD = os.environ.get("CACHE_PWD", "root")
CACHE_HOST = os.environ.get("CACHE_HOST", "localhost")
CACHE_PORT = os.environ.get("CACHE_PORT", "6379")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(f"redis://:{CACHE_PWD}@{CACHE_HOST}:{CACHE_PORT}")]
        }
    },
}



